### ISSUE TITLE
Accelerometer signature should match the sample

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/codal-brainpad#34]
It should be `MMA8453(I2C& _i2c, Pin& _int1, CoordinateSpace& coordinateSpace, uint16_t address = MMA8453_DEFAULT_ADDR,  uint16_t id = DEVICE_ID_ACCELEROMETER);`

**Comment by Arke64** [comment]
Updated, but need to find which concrete impl to pass.

**Comment by VictorDuma-zz** [comment]
I am sure there is the bug. Missing necessary functions in https://github.com/lancaster-university/codal-mbedos/blob/master/source/MbedI2C.cpp. Should contain the same as https://github.com/lancaster-university/codal-mbed/blob/master/source/MbedI2C.cpp#L63

**Comment by Arke64** [comment]
This part is done, opening another issue to track I2C.
