### ISSUE TITLE
Update to use the new display data format

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/codal-brainpad#39]
See Microsoft/pxt-brainpad#59

**Comment by VictorDuma-zz** [comment]
I guess, I missed the sense of this thread and don't understand what they need exactly. It was added memcpy(vram + 1, buffer, vramSize - 1); to the void BrainPadDisplay::writeScreenBuffer(uint8_t* buffer) but garbage on the screen like a result.

**Comment by Arke64** [comment]
They're changing the display format so it won't be garbage anymore

**Comment by Arke64** [comment]
Should be done now, waiting for confirmation.
