### ISSUE TITLE
Need to figure out which concrete impl to use for I2C

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/codal-brainpad#40]
codal::i2c is just a base class.

**Comment by VictorDuma-zz** [comment]
Can we use other than _mbed::I2C?

**Comment by Arke64** [comment]
It's being looked into, there's nothing for us to do here at the moment

**Comment by VictorDuma-zz** [comment]
yes. I added missed functions and locally codal::I2C works. https://github.com/lancaster-university/codal-core/issues/26

**Comment by pelikhan** [comment]
@VictorDuma @Arke64 could you look into creating a PR for codal-mbedos? What is the status here?

**Comment by Arke64** [comment]
@pelikhan do you mean a PR to update lancaster-university/codal-mbedos I2C to match what was done in codal-mbed, as mentnioed in lancaster-university/codal-core#26?

**Comment by pelikhan** [comment]
Yes similar to the PR that James mentionned.

**Comment by Arke64** [comment]
We'll take a look and see what we can do

**Comment by Arke64** [comment]
@pelikhan see lancaster-university/codal-mbedos#12

**Comment by Arke64** [comment]
Done in above PR, will keep using `codal::_mbed::I2C`

**Comment by pelikhan** [comment]
Do you have a new tag?

**Comment by Arke64** [comment]
We didn't have to change anything in BrainPad, we were already using `codal::_mbed::I2C`. We'll get a new tag as soon as we finish the display format change.
