### ISSUE TITLE
Make BrainPadLightSensor "like" an analog sensor

### ISSUE THREAD

**Issue by pelikhan** [ghi-electronics/codal-brainpad#48]
To make it easier to integrate, could you had the missing function to make the brainpadlightsensor look like an analog sensor.

This is the file https://github.com/Microsoft/pxt-common-packages/blob/master/libs/lightsensor/lightsensor.cpp that contains the use of that component. I will modify the file to use the brainpad type instead.

**Comment by VictorDuma-zz** [comment]
You mean do that like LightSensor::LightSensor(Pin &pin, uint16_t id) : codal::AnalogSensor(pin, id)

**Comment by pelikhan** [comment]
The code expects the same API set as an AnalogSensor class. 

See https://github.com/Microsoft/pxt-common-packages/blob/master/libs/lightsensor/lightsensor.cpp#L20 for example.

**Comment by VictorDuma-zz** [comment]
Done

**Comment by pelikhan** [comment]
I need a release tag in order to use any changes you made.
